version: "3.7"
 
services:
  polirural-policy-options-explorer:
    image: polirural-server:latest
    # build:
    #   context: ./
    ports:
      - 5000:5000 

  polirural-postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres    
      POSTGRES_PASSWORD: postgres    
      POSTGRES_DB: polirural
      PGDATA: "/var/lib/postgresql/data/pgdata" 
         
    ports:
     - 5434:5432